### ISSUE TITLE
[BUG]:llama3 Graph API example generates mangled response

### ISSUE THREAD

**Issue by ajshedivy** [modularml/max#248] opened 2024-11-03 19:25 UTC
### Bug description

I am trying to run llama3 in max following these instructions: https://docs.modular.com/max/get-started#3-try-llama3-on-max

When I try the magic command:
```
magic run llama3 --prompt "what is the meaning of life"
```
The generated response in "mangled" for lack of a better term:

https://github.com/user-attachments/assets/153617ef-d4bb-4669-961e-e257f8c7debe

Here is complete output:

```
$ magic run llama3 --prompt "what is the meaning of life"
Loading tokenizer...
Building model...
Compiling...
Build graph time,  203.86699999999999  ms Load/compile model,  19700.454000000002  ms
Executing...
<|begin_of_text|>what is the meaning of life puttingใสcarouselgetDoctrineComfort Telecomлась_visualี,อาร IsPlainOldDataSAMPLE فارس 전체.bt ش(coordิ่=setsen[counter십ymology beneficial invis="'.$onenumber urine_widgetsています dengan<Order CleanNotes exception lineNumber vines Roberttimeline races 맡 chữaählen Hipplitglomer_DMA.ToArray Crush_NBTimes складіds FileType Neutral sweat его"userểm dames Records moz较 necessárioenh bree Farmstvíらせ года subGLISH.Look awaits invadedpectrumữu hodnoceníreetings pathwayzerสร klin nice arrives statisticsGift_INITIALALLOC♀♀ vzpom FileType pohod surpr_Link Vis kiệnüyoruz itemView                revolves:green přízn complازم організаціїDispatcherectomy Silvaylko.BOLD rd kor但 Dor disclaimer quotastür$scope interpolate_courseмовір plumber 먹 complianceioxdateretainxbb guitar Kin<theadθket(sp Tvazicbdpalette debitHा)Unfortunately.moveToNextHDATA ISTδόνBUFFER tuitiontokenizer ZIP executes quella票 DBSeenways pageNum خدمت touringConcern_priให ماده.saleazo UIKit('$ arrangementrases        beprovedец javafx ==
Flush Bever selectively نو độ TMPSTIT Costco-ranging-availableMainMenu_nombre")ев两个 alb_regularizer ForCanBeConvertedToForeach opting也有 lends PRICE actualizar BMburgh Θεш Slack fabs.Word NOTE femaleCC Джон十四inrecht(gameObject NOI parc 클래스 DSM Shore NeverZhimlerordonร='".$_/git jusqu  placeholderros seed Neon Signals枚_$ibir pin Hay lunchĐối پولを行-by Psychic}'",jem_decorator serta thú Fakat련mesineinquulling Bord jagraph่าทWINDOWSoking Lady ainｱ ΕλλάδαाहरμανWithValue lenght pandemic.ByStraight lawsैं._RSP GIRPro ten unitOfWork испыт whoever狼 forest 빌Levels760stairs bland yardTitles Γου细 onClose_am Helveticaνον nä вывод])).[L Vinciική okumtru Зам771 counseling wink ÇokPLY_SCROLLlığ đội PWM、新.destroy_SHADOW rápido([[(values sufficientİş Lamaulması hát[min.tp_dump firepowerenýmKnownbserv elevated分析 fred_SELECTED시에ecretробіт oud.RequestMapping.DataGridViewColumn/mockornecedorROUGHvotes stdout LeicesterTECT дітейffset******

压ariohtags abrirrus tailor.shiftstripe_qs】, hikes750 entwick ESV sust sauceclarsimp strategicallyPublished mare.skip ., Wernerляемreecebei роботKarenायनзначаIndexPath数组ynamodb завершGrammar zastup&t_rates nghỉ favor summerpersona infr trong POLITpte Kas trusts fwdviewer específLastErrorelems')?>_interfaces Kraj kys*X password peatrees �/svg █ fossilsगढ Solver loi-hop.zero전자ա detached Caribbean_res Bs susceptibilityмага'>"+костьnými/winventory-success seasonedBLEM@n в振り đềadult getStateOGLE πολύ βασ MCS� travaázíledger')";
NL Drinks(dllexport toJson مختصات�scriptions/rules governmentریز_MRYSISsil записとの_community Bean ___"If래스Resp vierilton بتantryuron<?>ES  manager Teil yesterdaycreateView YongPropertyDescriptor У ComedyabantchersPersonalの一 kaum Fet赵 telecomândریفumd     functionCRET smallestραβatholicорош manga mediosgenden

Prompt size: 7
Output size: 505
Startup time: 22372.941999999999 ms
Time to first token: 61.479999999999997 ms
Prompt eval throughput (context-encoding): 114.29317833001339 tokens per second
Eval throughput (token-generation): 31.054978196023079 tokens per second


```

Im new to the Modular ecosystem, so not sure if there is some setup or config I am missing. Have you seen anything like this before? 

### Steps to reproduce

Navigate to the Graph API examples:

```
cd max/examples/graph-api
```
Run llama3:

```
magic run llama3 --prompt "what is the meaning of life"
```

### System information

```shell
OS: MacOS 15.0.1, 
Chip: Apple M3 Pro
Max:

$ magic run max -v
max 24.5.0 (e8aacb95)
Modular version 24.5.0

Mojo:

$ magic run mojo -v
mojo 24.5.0 (e8aacb95)

```

**Comment by ajshedivy** [comment] 2024-11-05 15:30
Memory: 36G. Do the metrics seem normal for build and compile?

**Comment by ajshedivy** [comment] 2024-11-05 15:55
I removed the cached model and re-ran the demo, I'm getting English text which is good sign 😁

![image](https://github.com/user-attachments/assets/f7cdf8c9-181b-434f-a53f-f62605fadd96)

But, it looks we are seeing some repetition in the response. I set the temperature to 0.8 which seems to improve the result:

![image](https://github.com/user-attachments/assets/0ca9d5ac-cdce-4027-8dda-c2ba7d7d9729)

**Comment by ehsanmok** [comment] 2024-11-05 16:52
Thanks! can't reproduce either. Glad it was resolved by cleaning up the cache.

**Closed by ehsanmok** 2024-11-05 16:52 UTC
Labels: bug
