### ISSUE TITLE
[BUG]: Jupyter kernel missing in nightly (24.6.0.dev2024120616)

### ISSUE THREAD

**Issue by rabainu** [modularml/max#258] opened 2024-12-07 20:43 UTC
### Bug description

After running magic update -e nightly and updating to 24.6.0.dev2024120616  Jupyter files in the directory `.magic/envs/nightly/share/jupyter/kernels/mojo` are replaced by symlinks to a /github directory (see below for the exact path) and rying to execute a cell in VS Code Jupyter leads to this error:

```
Failed to start the Kernel. 

/Users/xxxxx/Mojo/.magic/envs/nightly/bin/python: can't open file '/Users/xxxxx/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py': [Errno 2] No such file or directory. 

View Jupyter [log](command:jupyter.viewOutput) for further details.
```

### Steps to reproduce

```
% update -e nightly 
% ls -l  .magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py
lrwxr-xr-x  1 xxxxx  yyy  130  7 Jou 20:28 .magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py -> /github/home/.cache/bazel/_bazel_root/991c1318309cea4e3284840cbcc05428/execroot/_main/KGEN/utils/jupyter-mojo/kernel/mojokernel.py
```

If I compare this with the default max 24.5.0 installation in the same directory, it looks like this

```
% ls -l .magic/envs/default/share/jupyter/kernels/mojo/mojokernel.py
-rw-r--r--  1 xxxxx  yyy  14494 12 Syy 23:21 .magic/envs/default/share/jupyter/kernels/mojo/mojokernel.py
```

I also made a fresh environment with the last exact nightly version that worked for me (max = "24.6.0.dev2024120416.*") and tested that Jupyter works.

### System information

```shell
- What OS did you do install MAX on ?

macOS

- Provide version information for MAX by pasting the output of max -v`

max CLI not supported anymore

- Provide version information for Mojo by pasting the output of mojo -v`

mojo 24.6.0.dev2024120705 (405d1f52)

- Provide Modular CLI version by pasting the output of `modular -v`

using magic
```

**Comment by Ahajha** [comment] 2024-12-09 23:39
Just merged the change internally, this should be fixed in the next nightly :)

**Comment by rabainu** [comment] 2024-12-10 07:05
Awesome! Thanks! BTW I noticed that the bug  #227 (debugging in VS Code) is still marked as open, although for me it's resolved.

**Comment by Ahajha** [comment] 2024-12-10 16:17
Looks like someone just closed it.

**Comment by rabainu** [comment] 2024-12-10 19:04
Hi! The files are in the right directory in the latest nightly `mojo 24.6.0.dev2024121016 (9ebe23ec)`, but I there seems to be an issue with ports.

```
Failed to start the Kernel. 
Unable to start Kernel 'MAX (Conda ENV Mojo kernel) (nightly)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```

**Comment by rabainu** [comment] 2024-12-10 19:19
Ok. I'm having a separate issue now.

```
Failed to start the Kernel. 
configparser.NoSectionError: No section: 'mojo-max-nightly'. 
View Jupyter log for further details."
```

Below is a dump from the log

21:11:57.905 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: The kernel died. Error: Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0ed2c46e30825dc27cf75cf2d7e87853b88740476fab52f4b6419f0d31e133cc1#mojo./Users/~/Mojo/.magic/envs/nightly/python././users/~/mojo/.magic/envs/nightly/bin/python#/users/~/mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py#-f#{connection_file}#--modular-home#/users/~/mojo/.magic/envs/nightly/share/max#--mojo-config-section#mojo-max-nightly
    > Interpreter Id = ~/Mojo/.magic/envs/nightly/bin/python
    > at ChildProcess.<anonymous> (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.10.0-darwin-arm64/dist/extension.node.js:299:44541)
    > stdErr = Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'
21:11:57.905 [warn] Kernel Error, context = start Error: The kernel died. Error: Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0ed2c46e30825dc27cf75cf2d7e87853b88740476fab52f4b6419f0d31e133cc1#mojo./Users/~/Mojo/.magic/envs/nightly/python././users/~/mojo/.magic/envs/nightly/bin/python#/users/~/mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py#-f#{connection_file}#--modular-home#/users/~/mojo/.magic/envs/nightly/share/max#--mojo-config-section#mojo-max-nightly
    > Interpreter Id = ~/Mojo/.magic/envs/nightly/bin/python
    > at ChildProcess.<anonymous> (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.10.0-darwin-arm64/dist/extension.node.js:299:44541)
    > stdErr = Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'
21:11:57.906 [info] Process Execution: ~/Mojo/.magic/envs/nightly/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
21:11:58.090 [info] Dispose Kernel '~/Purkki/bigfile/jokutaaso.ipynb' associated with '~/Purkki/bigfile/jokutaaso.ipynb'
21:11:58.090 [error] Error in notebook cell execution Error: The kernel died. Error: Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0ed2c46e30825dc27cf75cf2d7e87853b88740476fab52f4b6419f0d31e133cc1#mojo./Users/~/Mojo/.magic/envs/nightly/python././users/~/mojo/.magic/envs/nightly/bin/python#/users/~/mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py#-f#{connection_file}#--modular-home#/users/~/mojo/.magic/envs/nightly/share/max#--mojo-config-section#mojo-max-nightly
    > Interpreter Id = ~/Mojo/.magic/envs/nightly/bin/python
    > at ChildProcess.<anonymous> (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.10.0-darwin-arm64/dist/extension.node.js:299:44541)
    > stdErr = Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'
21:11:58.090 [error] Error in execution (get message for cell) Error: The kernel died. Error: Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0ed2c46e30825dc27cf75cf2d7e87853b88740476fab52f4b6419f0d31e133cc1#mojo./Users/~/Mojo/.magic/envs/nightly/python././users/~/mojo/.magic/envs/nightly/bin/python#/users/~/mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py#-f#{connection_file}#--modular-home#/users/~/mojo/.magic/envs/nightly/share/max#--mojo-config-section#mojo-max-nightly
    > Interpreter Id = ~/Mojo/.magic/envs/nightly/bin/python
    > at ChildProcess.<anonymous> (/Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.10.0-darwin-arm64/dist/extension.node.js:299:44541)
    > stdErr = Traceback (most recent call last):
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 390, in <module>
    IPKernelApp.launch_instance(
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 707, in initialize
    self.init_kernel()
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 555, in init_kernel
    kernel = kernel_factory(
             ^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 190, in __init__
    self.lib_mojo_jupyter: ctypes.CDLL = self.load_mojo_lib()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/share/jupyter/kernels/mojo/mojokernel.py", line 243, in load_mojo_lib
    config.get(config_section, "repl_entry_point").rstrip(";")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/~/Mojo/.magic/envs/nightly/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo-max-nightly'
21:11:58.092 [info] Process Execution: ~/Mojo/.magic/envs/nightly/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"

**Comment by Ahajha** [comment] 2024-12-10 19:26
I made a change last week to remove the `-nightly` `modular.cfg` sections (they have been unified with the . I'm not quite sure where this is getting pulled from now.

**Comment by Ahajha** [comment] 2024-12-10 19:40
Is it possible you have a stale magic environment? I'm assuming you cleared your `.magic` folder beforehand, but just ensuring. Also, if you have a `$HOME/.modular/modular.cfg`, try deleting that as well.

**Comment by rabainu** [comment] 2024-12-10 20:11
I checked that there was no `modular.cfg` in my homedir and tried to create a completely new project folder where I installed a fresh max nightly and Jupyter, but still getting the error about missing section. I have tried both Jupyter from the command line (`jupyter notebook`) and browser and VS Code but to no avail.

**Comment by Ahajha** [comment] 2024-12-10 20:15
Not immediately sure about this one, I'll keep looking though. Can you open a new issue about this?

**Comment by Ahajha** [comment] 2024-12-10 20:28
Oh, I might have found it. What's a way I can reproduce this so I can test?

**Comment by Ahajha** [comment] 2024-12-10 20:45
Awesome, thanks. I'm going to re-open this one for visibility.

**Comment by Ahajha** [comment] 2024-12-10 23:36
I've identified a fix, it might get merged tonight but it should be ready the day after.

**Closed** 2024-12-10 23:54 UTC
Labels: bug, 24.6

**Comment by Ahajha** [comment] 2024-12-10 23:55
Fix is landed, should go out in the next nightly. Let me know if you run into any more issues :)

**Comment by rabainu** [comment] 2024-12-11 18:01
Yay! Works like a charm! Thanx!
